  WORKSPACENAME: mlw-trunkbased-dev
  RESOURCEGROUPNAME: mlops-trunkbased-dev
  STORAGEACCOUNTNAME: aamldatalake
  LOCATION: eastus2
  KEYVAULTNAME: kv-trunkbased-dev
  ENVPREFIX: dev
  MODELNAME: hate-pt-speech
  DESCRIPTION: 'A hate detection model for tweets in portuguese'
  CONDAENVNAME: transformers-torch-19