channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.2.4
  - pip:
      - mlflow-skinny==1.25.0
      - azureml-mlflow==1.41.0
      - urllib3<=1.26.7,>=1.23
      - msrest==0.6.21
      - protobuf~=3.19.0
      - torch==1.9
      - transformers==4.10
      - tensorboard==2.6
      - pandas==1.3
      - numpy==1.19
      - scikit-learn==1.1.1
      - statsmodels==0.13.1
      - jobtools
