$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
display_name: hate-pt-speech
experiment_name: hate-pt-speech
description: Trains a model to clasificate tweets text according to hate/no hate
code: ../../../src/
command: >-
  jobtools hatedetection.train.trainer train_and_evaluate \
            --input-dataset ${{inputs.input_dataset}} \
            --eval-dataset ${{inputs.eval_dataset}} \
            --params ${{inputs.params}}
inputs:
  input_dataset:
    path: azureml:portuguese-hate-speech-tweets:1
  eval_dataset:
    path: azureml:portuguese-hate-speech-tweets-eval:1
  params:
    type: uri_file
    path: ./train.params.yml
    mode: download
environment: azureml:transformers-torch-19:14
compute: azureml:gpuprdev